/**
 * Single Source of Truth for DMS Hub Endpoints
 * 
 * This file is automatically generated and should not be edited manually.
 * It reflects the real state of the backend endpoints.
 */

export type Endpoint = {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  description: string;
  status: 'OK' | 'BROKEN' | 'MISSING' | 'LEGACY';
  category: 'DMS Hub' | 'GIS' | 'Abacus' | 'Guardian' | 'Legacy';
};

export const realEndpoints: Endpoint[] = [
  // DMS Hub
  {
    method: 'GET',
    path: '/api/dmsHub/markets/list',
    description: 'Lista mercati con statistiche',
    status: 'OK',
    category: 'DMS Hub',
  },
  {
    method: 'GET',
    path: '/api/dmsHub/markets/getById',
    description: 'Dettagli mercato per ID',
    status: 'OK',
    category: 'DMS Hub',
  },
  {
    method: 'GET',
    path: '/api/dmsHub/stalls/listByMarket',
    description: 'Lista posteggi per mercato',
    status: 'OK',
    category: 'DMS Hub',
  },
  {
    method: 'GET',
    path: '/api/dmsHub/vendors/list',
    description: 'Lista venditori',
    status: 'OK',
    category: 'DMS Hub',
  },
  {
    method: 'GET',
    path: '/api/dmsHub/concessions/list',
    description: 'Lista concessioni',
    status: 'OK',
    category: 'DMS Hub',
  },
  {
    method: 'GET',
    path: '/api/dmsHub/stalls/byCode/:stallCode',
    description: 'Get stall by full_code',
    status: 'OK',
    category: 'DMS Hub',
  },
  {
    method: 'POST',
    path: '/api/dmsHub/stalls/updateStatus',
    description: 'Aggiorna stato posteggio',
    status: 'MISSING',
    category: 'DMS Hub',
  },
  // GIS
  {
    method: 'GET',
    path: '/api/gis/health',
    description: 'Health check GIS',
    status: 'OK',
    category: 'GIS',
  },
  {
    method: 'GET',
    path: '/api/gis/market-map',
    description: 'Mappa mercato Grosseto',
    status: 'OK',
    category: 'GIS',
  },
  // Abacus
  {
    method: 'POST',
    path: '/api/abacus/sql/query',
    description: 'Esegue una query SQL',
    status: 'OK',
    category: 'Abacus',
  },
  {
    method: 'GET',
    path: '/api/abacus/sql/tables',
    description: 'Lista tabelle database',
    status: 'OK',
    category: 'Abacus',
  },
  // Guardian
  {
    method: 'GET',
    path: '/api/guardian/health',
    description: 'Health check Guardian',
    status: 'OK',
    category: 'Guardian',
  },
  // Legacy
  {
    method: 'GET',
    path: '/api/markets',
    description: 'Endpoint legacy markets',
    status: 'LEGACY',
    category: 'Legacy',
  },
];
