/**
 * API Inventory Service
 * 
 * Servizio centralizzato per l'inventario di tutti gli endpoint API disponibili
 * nel sistema DMS Hub (tRPC + Legacy REST API).
 * 
 * Utilizzato dalla sezione "Integrazioni" della Dashboard PA per mostrare
 * l'elenco completo delle API disponibili, il loro stato, e la documentazione.
 */

export interface APIEndpoint {
  id: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  path: string;
  description: string;
  category: 'analytics' | 'integrations' | 'mobility' | 'logs' | 'system' | 'guardian' | 'dms' | 'carbon' | 'users' | 'sustainability' | 'businesses' | 'inspections' | 'notifications' | 'civic' | 'wallet' | 'imprese' | 'suap' | 'concessioni' | 'tariffe' | 'qualificazioni' | 'tcc' | 'gaming' | 'pdnd' | 'appio';
  status: 'active' | 'deprecated' | 'beta' | 'maintenance';
  version: string;
  requiresAuth: boolean;
  rateLimit?: string;
  documentation?: string;
  testParams?: Record<string, any>;
}

/**
 * Inventario completo degli endpoint tRPC disponibili nel sistema DMS Hub
 */
export function getAPIInventory(): APIEndpoint[] {
  return [
    // ============================================================================
    // SYSTEM & AUTH
    // ============================================================================
    {
      id: 'system.health',
      method: 'GET',
      path: '/api/system/health',
      description: 'Verifica lo stato di salute del sistema',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: false,
      documentation: 'Ritorna lo stato di salute del sistema (database, API, servizi esterni)',
    },
    {
      id: 'auth.me',
      method: 'GET',
      path: '/api/auth/me',
      description: 'Ottieni informazioni sull\'utente corrente',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i dati dell\'utente autenticato',
    },
    {
      id: 'auth.logout',
      method: 'POST',
      path: '/api/auth/logout',
      description: 'Effettua il logout dell\'utente',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Invalida la sessione corrente e rimuove il cookie di autenticazione',
    },

    // ============================================================================
    // FIREBASE AUTH (v2.0)
    // ============================================================================
    {
      id: 'auth.firebase.sync',
      method: 'POST',
      path: '/api/auth/firebase/sync',
      description: 'Sincronizza utente Firebase con MioHub (crea/aggiorna profilo)',
      category: 'system',
      status: 'active',
      version: '2.0',
      requiresAuth: true,
      documentation: 'Riceve un Firebase ID Token, lo verifica con Firebase Admin SDK, crea o aggiorna il profilo utente nel database MioHub e restituisce il profilo unificato con ruoli e permessi.',
    },
    {
      id: 'auth.firebase.verify',
      method: 'POST',
      path: '/api/auth/firebase/verify',
      description: 'Verifica validità di un Firebase ID Token',
      category: 'system',
      status: 'active',
      version: '2.0',
      requiresAuth: true,
      documentation: 'Verifica un Firebase ID Token e restituisce i dati decodificati (uid, email, provider). Utilizzato per validare sessioni esistenti.',
    },
    {
      id: 'auth.firebase.me',
      method: 'GET',
      path: '/api/auth/firebase/me',
      description: 'Ottieni profilo utente Firebase corrente',
      category: 'system',
      status: 'active',
      version: '2.0',
      requiresAuth: true,
      documentation: 'Restituisce il profilo completo dell\'utente autenticato tramite Firebase, inclusi ruoli e permessi MioHub.',
    },
    {
      id: 'auth.firebase.logout',
      method: 'POST',
      path: '/api/auth/firebase/logout',
      description: 'Logout utente Firebase e invalidazione sessione',
      category: 'system',
      status: 'active',
      version: '2.0',
      requiresAuth: true,
      documentation: 'Effettua il logout dell\'utente Firebase, invalida la sessione lato server e rimuove i cookie.',
    },
    {
      id: 'auth.login',
      method: 'POST',
      path: '/api/auth/login',
      description: 'Login legacy con email/password (fallback)',
      category: 'system',
      status: 'active',
      version: '2.0',
      requiresAuth: false,
      documentation: 'Endpoint di login legacy per compatibilità. Accetta email e password, restituisce profilo utente.',
    },
    {
      id: 'auth.register',
      method: 'POST',
      path: '/api/auth/register',
      description: 'Registrazione nuovo utente con email/password',
      category: 'system',
      status: 'active',
      version: '2.0',
      requiresAuth: false,
      documentation: 'Registra un nuovo utente nel sistema con email e password. Crea il profilo Firebase e il profilo MioHub.',
    },
    {
      id: 'auth.config',
      method: 'GET',
      path: '/api/auth/config',
      description: 'Configurazione pubblica Firebase per il client',
      category: 'system',
      status: 'active',
      version: '2.0',
      requiresAuth: false,
      documentation: 'Restituisce la configurazione Firebase pubblica (apiKey, authDomain, projectId) necessaria per inizializzare il client SDK.',
    },

    // ============================================================================
    // ANALYTICS
    // ============================================================================
    {
      id: 'analytics.overview',
      method: 'GET',
      path: '/api/analytics/overview',
      description: 'Statistiche generali della piattaforma',
      category: 'analytics',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna statistiche aggregate su mercati, negozi, transazioni, check-in',
    },
    {
      id: 'analytics.markets',
      method: 'GET',
      path: '/api/analytics/markets',
      description: 'Elenco mercati con statistiche',
      category: 'analytics',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco completo dei mercati con statistiche aggregate',
    },
    {
      id: 'analytics.shops',
      method: 'GET',
      path: '/api/analytics/shops',
      description: 'Elenco negozi con statistiche',
      category: 'analytics',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco completo dei negozi con statistiche aggregate',
    },
    {
      id: 'analytics.transactions',
      method: 'GET',
      path: '/api/analytics/transactions',
      description: 'Elenco transazioni recenti',
      category: 'analytics',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna le transazioni recenti con dettagli',
    },
    {
      id: 'analytics.checkins',
      method: 'GET',
      path: '/api/analytics/checkins',
      description: 'Elenco check-in operatori',
      category: 'analytics',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i check-in degli operatori nei mercati',
    },
    {
      id: 'analytics.products',
      method: 'GET',
      path: '/api/analytics/products',
      description: 'Elenco prodotti con statistiche',
      category: 'analytics',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco dei prodotti con statistiche di vendita',
    },
    {
      id: 'analytics.productTracking',
      method: 'GET',
      path: '/api/analytics/productTracking',
      description: 'Tracciamento prodotti (blockchain)',
      category: 'analytics',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i dati di tracciamento blockchain dei prodotti',
    },

    // ============================================================================
    // CARBON CREDITS
    // ============================================================================
    {
      id: 'carbonCredits.config',
      method: 'GET',
      path: '/api/carbonCredits/config',
      description: 'Configurazione crediti di carbonio',
      category: 'carbon',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna la configurazione del sistema di crediti di carbonio',
    },
    {
      id: 'carbonCredits.fundTransactions',
      method: 'GET',
      path: '/api/carbonCredits/fundTransactions',
      description: 'Transazioni fondo crediti carbonio',
      category: 'carbon',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna le transazioni del fondo crediti di carbonio',
    },
    {
      id: 'carbonCredits.reimbursements',
      method: 'GET',
      path: '/api/carbonCredits/reimbursements',
      description: 'Rimborsi crediti carbonio',
      category: 'carbon',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i rimborsi effettuati tramite crediti di carbonio',
    },

    // ============================================================================
    // LOGS
    // ============================================================================
    {
      id: 'logs.system',
      method: 'GET',
      path: '/api/logs/system',
      description: 'Log di sistema',
      category: 'logs',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i log di sistema (API calls, database queries, errors)',
    },

    // ============================================================================
    // USERS
    // ============================================================================
    {
      id: 'users.analytics',
      method: 'GET',
      path: '/api/users/analytics',
      description: 'Statistiche utenti',
      category: 'users',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna le statistiche sugli utenti della piattaforma',
    },

    // ============================================================================
    // SUSTAINABILITY
    // ============================================================================
    {
      id: 'sustainability.metrics',
      method: 'GET',
      path: '/api/sustainability/metrics',
      description: 'Metriche di sostenibilità',
      category: 'sustainability',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna le metriche di sostenibilità ambientale',
    },

    // ============================================================================
    // BUSINESSES
    // ============================================================================
    {
      id: 'businesses.list',
      method: 'GET',
      path: '/api/businesses/list',
      description: 'Elenco attività commerciali',
      category: 'businesses',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco delle attività commerciali registrate',
    },

    // ============================================================================
    // INSPECTIONS
    // ============================================================================
    {
      id: 'inspections.list',
      method: 'GET',
      path: '/api/inspections/list',
      description: 'Elenco ispezioni e violazioni',
      category: 'inspections',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco delle ispezioni e violazioni registrate',
    },

    // ============================================================================
    // NOTIFICATIONS
    // ============================================================================
    {
      id: 'notifications.list',
      method: 'GET',
      path: '/api/notifications/list',
      description: 'Elenco notifiche',
      category: 'notifications',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco delle notifiche per l\'utente corrente',
    },

    // ============================================================================
    // CIVIC REPORTS
    // ============================================================================
    {
      id: 'civicReports.list',
      method: 'GET',
      path: '/api/civicReports/list',
      description: 'Elenco segnalazioni civiche',
      category: 'civic',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco delle segnalazioni civiche',
    },

    // ============================================================================
    // MOBILITY (TPER)
    // ============================================================================
    {
      id: 'mobility.list',
      method: 'GET',
      path: '/api/mobility/list',
      description: 'Dati mobilità TPER',
      category: 'mobility',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i dati di mobilità TPER (fermate, linee, orari)',
    },

    // ============================================================================
    // INTEGRATIONS - TPER
    // ============================================================================
    {
      id: 'integrations.tper.stops',
      method: 'GET',
      path: '/api/integrations/tper/stops',
      description: 'Lista fermate TPER Bologna',
      category: 'integrations',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco completo delle fermate TPER a Bologna',
    },
    {
      id: 'integrations.tper.sync',
      method: 'POST',
      path: '/api/integrations/tper/sync',
      description: 'Sincronizza dati TPER',
      category: 'integrations',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Sincronizza i dati TPER (fermate, linee, orari) dal portale Open Data di Bologna',
    },

    // ============================================================================
    // DMS HUB
    // ============================================================================
    // DMS HUB - Markets
    {
      id: 'dmsHub.markets.list',
      method: 'GET',
      path: '/api/trpc/dmsHub.markets.list',
      description: 'Lista tutti i mercati',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco dei mercati gestiti dal sistema DMS',
    },
    {
      id: 'dmsHub.markets.getById',
      method: 'GET',
      path: '/api/trpc/dmsHub.markets.getById',
      description: 'Dettagli mercato con geometria',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i dettagli completi di un mercato specifico',
      testParams: { id: 1 },
    },
    {
      id: 'dmsHub.markets.importAuto',
      method: 'POST',
      path: '/api/trpc/dmsHub.markets.importAuto',
      description: 'Import automatico da Slot Editor v3 (senza richiedere nome/città)',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Importa automaticamente i dati del mercato da Slot Editor v3',
    },
    {
      id: 'dmsHub.markets.importFromSlotEditor',
      method: 'GET',
      path: '/api/trpc/dmsHub.markets.importFromSlotEditor',
      description: 'MERCATI - Import da Slot Editor v3',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Importa mercato con nome e città da Slot Editor v3',
    },
    // DMS HUB - Stalls
    {
      id: 'dmsHub.stalls.listByMarket',
      method: 'GET',
      path: '/api/trpc/dmsHub.stalls.listByMarket',
      description: 'POSTEGGI - Gestione e stati',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco dei posteggi per un mercato specifico',
      testParams: { marketId: 1 },
    },
    {
      id: 'dmsHub.stalls.updateStatus',
      method: 'POST',
      path: '/api/trpc/dmsHub.stalls.updateStatus',
      description: 'Aggiorna stato posteggio',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna lo stato di un posteggio (libero, occupato, riservato)',
    },
    {
      id: 'dmsHub.stalls.getStatuses',
      method: 'GET',
      path: '/api/trpc/dmsHub.stalls.getStatuses',
      description: 'Stati real-time tutti i posteggi di un mercato',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna gli stati in tempo reale di tutti i posteggi',
      testParams: { marketId: 1 },
    },
    {
      id: 'stalls.stats.totals',
      method: 'GET',
      path: '/api/stalls/stats/totals',
      description: 'Statistiche aggregate posteggi: totali, occupati, liberi, in assegnazione',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: false,
      documentation: 'Ritorna le statistiche aggregate di tutti i posteggi (REST endpoint su Hetzner)',
    },
    // DMS HUB - Vendors
    {
      id: 'dmsHub.vendors.list',
      method: 'GET',
      path: '/api/trpc/dmsHub.vendors.list',
      description: 'Lista operatori/venditori',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco degli operatori registrati',
    },
    {
      id: 'dmsHub.vendors.create',
      method: 'POST',
      path: '/api/trpc/dmsHub.vendors.create',
      description: 'Crea nuovo operatore',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Registra un nuovo operatore nel sistema',
    },
    {
      id: 'dmsHub.vendors.update',
      method: 'POST',
      path: '/api/trpc/dmsHub.vendors.update',
      description: 'Aggiorna operatore',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna i dati di un operatore esistente',
    },
    {
      id: 'dmsHub.vendors.getFullDetails',
      method: 'GET',
      path: '/api/trpc/dmsHub.vendors.getFullDetails',
      description: 'Dettagli completi operatore',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna tutti i dettagli di un operatore con concessioni e wallet',
      testParams: { vendorId: 1 },
    },
    // DMS HUB - Bookings (Prenotazioni)
    {
      id: 'dmsHub.bookings.create',
      method: 'GET',
      path: '/api/trpc/dmsHub.bookings.create',
      description: 'PRENOTAZIONI - Sistema booking posteggi',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea una nuova prenotazione per un posteggio',
    },
    {
      id: 'dmsHub.bookings.listActive',
      method: 'GET',
      path: '/api/trpc/dmsHub.bookings.listActive',
      description: 'Lista prenotazioni attive',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna le prenotazioni attive per oggi',
    },
    {
      id: 'dmsHub.bookings.confirmCheckin',
      method: 'GET',
      path: '/api/trpc/dmsHub.bookings.confirmCheckin',
      description: 'Conferma check-in',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Conferma il check-in di una prenotazione',
    },
    {
      id: 'dmsHub.bookings.cancel',
      method: 'POST',
      path: '/api/trpc/dmsHub.bookings.cancel',
      description: 'Cancella prenotazione',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Cancella una prenotazione esistente',
    },
    // DMS HUB - Presences (Presenze)
    {
      id: 'dmsHub.presences.checkout',
      method: 'GET',
      path: '/api/trpc/dmsHub.presences.checkout',
      description: 'PRESENZE - Check-in/Check-out',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Registra il check-out di un operatore',
    },
    {
      id: 'dmsHub.presences.getTodayByMarket',
      method: 'GET',
      path: '/api/trpc/dmsHub.presences.getTodayByMarket',
      description: 'Presenze oggi per mercato',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna le presenze di oggi per un mercato',
      testParams: { marketId: 1 },
    },
    // DMS HUB - Inspections (Controlli)
    {
      id: 'dmsHub.inspections.create',
      method: 'GET',
      path: '/api/trpc/dmsHub.inspections.create',
      description: 'CONTROLLI E VERBALI - Per App Polizia',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea un nuovo controllo/verbale',
    },
    {
      id: 'dmsHub.inspections.list',
      method: 'GET',
      path: '/api/trpc/dmsHub.inspections.list',
      description: 'Lista controlli',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco dei controlli effettuati',
    },
    // DMS HUB - Violations (Violazioni)
    {
      id: 'dmsHub.violations.create',
      method: 'POST',
      path: '/api/trpc/dmsHub.violations.create',
      description: 'Crea violazione',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Registra una nuova violazione',
    },
    {
      id: 'dmsHub.violations.list',
      method: 'GET',
      path: '/api/trpc/dmsHub.violations.list',
      description: 'Lista violazioni',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco delle violazioni registrate',
    },
    // DMS HUB - Hub Locations
    {
      id: 'dmsHub.hub.locations.list',
      method: 'GET',
      path: '/api/trpc/dmsHub.hub.locations.list',
      description: 'Lista sedi HUB',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco delle sedi HUB',
    },
    {
      id: 'dmsHub.hub.locations.getById',
      method: 'GET',
      path: '/api/trpc/dmsHub.hub.locations.getById',
      description: 'getById endpoint',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i dettagli di una sede HUB',
      testParams: { id: 1 },
    },
    {
      id: 'dmsHub.hub.locations.create',
      method: 'GET',
      path: '/api/trpc/dmsHub.hub.locations.create',
      description: 'create endpoint',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea una nuova sede HUB',
    },
    {
      id: 'dmsHub.hub.locations.update',
      method: 'GET',
      path: '/api/trpc/dmsHub.hub.locations.update',
      description: 'update endpoint',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna una sede HUB',
    },
    {
      id: 'dmsHub.hub.locations.delete',
      method: 'POST',
      path: '/api/trpc/dmsHub.hub.locations.delete',
      description: 'delete endpoint',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Elimina una sede HUB',
    },
    // DMS HUB - Hub Shops
    {
      id: 'dmsHub.hub.shops.list',
      method: 'GET',
      path: '/api/trpc/dmsHub.hub.shops.list',
      description: 'Gestione negozi HUB',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco dei negozi in una sede HUB',
      testParams: { hubId: 1 },
    },
    {
      id: 'dmsHub.hub.shops.create',
      method: 'GET',
      path: '/api/trpc/dmsHub.hub.shops.create',
      description: 'create endpoint',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea un nuovo negozio in una sede HUB',
    },
    // DMS HUB - Hub Services
    {
      id: 'dmsHub.hub.services.list',
      method: 'GET',
      path: '/api/trpc/dmsHub.hub.services.list',
      description: 'Gestione servizi HUB',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco dei servizi disponibili in una sede HUB',
      testParams: { hubId: 1 },
    },
    {
      id: 'dmsHub.hub.services.create',
      method: 'GET',
      path: '/api/trpc/dmsHub.hub.services.create',
      description: 'create endpoint',
      category: 'dms',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea un nuovo servizio in una sede HUB',
    },

    // ============================================================================
    // MIO AGENT
    // ============================================================================
    {
      id: 'mioAgent.getLogs',
      method: 'GET',
      path: '/api/mioAgent/getLogs',
      description: 'Log agente MIO',
      category: 'logs',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i log dell\'agente MIO dal repository GitHub',
    },

    // ============================================================================
    // MIHUB (Multi-Agent System)
    // ============================================================================
    {
      id: 'mihub.createTask',
      method: 'POST',
      path: '/api/trpc/mihub.createTask',
      description: 'Crea task per agente',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea un nuovo task da assegnare a un agente',
    },
    {
      id: 'mihub.getTasks',
      method: 'GET',
      path: '/api/trpc/mihub.getTasks',
      description: 'Lista task agenti',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco dei task degli agenti',
    },
    {
      id: 'mihub.updateTaskStatus',
      method: 'POST',
      path: '/api/trpc/mihub.updateTaskStatus',
      description: 'Aggiorna stato task',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna lo stato di un task (pending, in_progress, completed, failed)',
    },
    {
      id: 'mihub.sendMessage',
      method: 'POST',
      path: '/api/trpc/mihub.sendMessage',
      description: 'Invia messaggio tra agenti',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Invia un messaggio da un agente a un altro',
    },
    {
      id: 'mihub.getMessages',
      method: 'GET',
      path: '/api/trpc/mihub.getMessages',
      description: 'Lista messaggi agente',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i messaggi ricevuti da un agente',
    },
    {
      id: 'mihub.markMessageAsRead',
      method: 'POST',
      path: '/api/trpc/mihub.markMessageAsRead',
      description: 'Segna messaggio come letto',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Segna un messaggio come letto',
    },
    {
      id: 'mihub.saveBrainMemory',
      method: 'POST',
      path: '/api/trpc/mihub.saveBrainMemory',
      description: 'Salva memoria agente',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Salva la memoria persistente di un agente',
    },
    {
      id: 'mihub.getBrainMemory',
      method: 'GET',
      path: '/api/trpc/mihub.getBrainMemory',
      description: 'Leggi memoria agente',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Legge la memoria persistente di un agente',
    },
    {
      id: 'mihub.setBagValue',
      method: 'POST',
      path: '/api/trpc/mihub.setBagValue',
      description: 'Imposta valore DataBag',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Imposta un valore nel DataBag condiviso',
    },
    {
      id: 'mihub.getBagValue',
      method: 'GET',
      path: '/api/trpc/mihub.getBagValue',
      description: 'Leggi valore DataBag',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Legge un valore dal DataBag condiviso',
    },
    {
      id: 'mihub.deleteBagValue',
      method: 'POST',
      path: '/api/trpc/mihub.deleteBagValue',
      description: 'Elimina valore DataBag',
      category: 'system',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Elimina un valore dal DataBag condiviso',
    },

    // ============================================================================
    // GUARDIAN (API Monitoring & Debug)
    // ============================================================================
    {
      id: 'guardian.integrations',
      method: 'GET',
      path: '/api/guardian/integrations',
      description: 'Inventario API completo',
      category: 'guardian',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'inventario completo di tutte le API disponibili nel sistema',
    },
    {
      id: 'guardian.logs',
      method: 'GET',
      path: '/api/guardian/logs',
      description: 'Log Guardian centralizzati',
      category: 'guardian',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i log centralizzati del sistema Guardian (API calls, errors, security)',
    },
    {
      id: 'guardian.debug.testEndpoint',
      method: 'POST',
      path: '/api/guardian/debug/testEndpoint',
      description: 'Test endpoint API',
      category: 'guardian',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Proxy per testare endpoint API dalla Dashboard PA',
      testParams: {
        endpoint: '/api/analytics/overview',
        method: 'GET',
        params: {},
      },
    },

    // ============================================================================
    // WALLET / PAGOPA - Sistema borsellino elettronico operatori mercatali
    // ============================================================================
    {
      id: 'wallet.stats',
      method: 'GET',
      path: '/api/trpc/wallet.stats',
      description: 'Statistiche generali wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna statistiche aggregate sui wallet: totale attivi, bloccati, saldo complessivo, avvisi PagoPA',
    },
    {
      id: 'wallet.list',
      method: 'GET',
      path: '/api/trpc/wallet.list',
      description: 'Lista wallet operatori',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco completo dei wallet operatori con saldo e stato',
    },
    {
      id: 'wallet.getById',
      method: 'GET',
      path: '/api/trpc/wallet.getById',
      description: 'Dettaglio wallet per ID',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i dettagli di un wallet specifico incluse le ultime transazioni',
      testParams: { walletId: 1 },
    },
    {
      id: 'wallet.getByImpresa',
      method: 'GET',
      path: '/api/trpc/wallet.getByImpresa',
      description: 'Wallet per impresa',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna il wallet associato a una specifica impresa',
      testParams: { impresaId: 1 },
    },
    {
      id: 'wallet.create',
      method: 'POST',
      path: '/api/trpc/wallet.create',
      description: 'Crea nuovo wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea un nuovo wallet per un operatore mercatale',
    },
    {
      id: 'wallet.updateStatus',
      method: 'POST',
      path: '/api/trpc/wallet.updateStatus',
      description: 'Aggiorna stato wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Modifica lo stato di un wallet (ATTIVO, BLOCCATO, SOSPESO)',
    },
    {
      id: 'wallet.transazioni',
      method: 'GET',
      path: '/api/trpc/wallet.transazioni',
      description: 'Storico transazioni wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna lo storico delle transazioni di un wallet (ricariche, decurtazioni)',
      testParams: { walletId: 1 },
    },
    {
      id: 'wallet.ricarica',
      method: 'POST',
      path: '/api/trpc/wallet.ricarica',
      description: 'Ricarica wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Effettua una ricarica manuale sul wallet (bonifico, contanti)',
    },
    {
      id: 'wallet.decurtazione',
      method: 'POST',
      path: '/api/trpc/wallet.decurtazione',
      description: 'Decurtazione wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Effettua una decurtazione dal wallet (presenza mercato, sanzione)',
    },
    {
      id: 'wallet.generaAvvisoPagopa',
      method: 'POST',
      path: '/api/trpc/wallet.generaAvvisoPagopa',
      description: 'PAGOPA - Genera avviso di pagamento',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Genera un avviso di pagamento PagoPA tramite E-FIL Plug&Pay per ricarica wallet',
    },
    {
      id: 'wallet.pagamentoSpontaneo',
      method: 'POST',
      path: '/api/trpc/wallet.pagamentoSpontaneo',
      description: 'PAGOPA - Pagamento spontaneo',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Avvia un pagamento spontaneo PagoPA con redirect al checkout',
    },
    {
      id: 'wallet.verificaPagamento',
      method: 'GET',
      path: '/api/trpc/wallet.verificaPagamento',
      description: 'PAGOPA - Verifica pagamento',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Verifica lo stato di un pagamento PagoPA tramite IUV',
      testParams: { iuv: 'RF0123456789012345678' },
    },
    {
      id: 'wallet.generaPdfAvviso',
      method: 'GET',
      path: '/api/trpc/wallet.generaPdfAvviso',
      description: 'PAGOPA - Genera PDF avviso',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Genera il PDF dell\'avviso di pagamento PagoPA',
    },
    {
      id: 'wallet.generaPdfQuietanza',
      method: 'GET',
      path: '/api/trpc/wallet.generaPdfQuietanza',
      description: 'PAGOPA - Genera PDF quietanza',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Genera il PDF della quietanza di pagamento PagoPA',
    },
    {
      id: 'wallet.avvisiPagopa',
      method: 'GET',
      path: '/api/trpc/wallet.avvisiPagopa',
      description: 'Lista avvisi PagoPA',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna gli avvisi PagoPA associati a un wallet',
      testParams: { walletId: 1 },
    },
    {
      id: 'wallet.tariffe',
      method: 'GET',
      path: '/api/trpc/wallet.tariffe',
      description: 'Tariffe posteggio',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna le tariffe giornaliere per tipo posteggio',
    },
    {
      id: 'wallet.verificaSaldoPresenza',
      method: 'POST',
      path: '/api/trpc/wallet.verificaSaldoPresenza',
      description: 'Verifica saldo per presenza',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Verifica se il saldo wallet è sufficiente per effettuare una presenza al mercato',
    },
    {
      id: 'wallet.ricercaPagamentiGiornalieri',
      method: 'GET',
      path: '/api/trpc/wallet.ricercaPagamentiGiornalieri',
      description: 'PAGOPA - Ricerca pagamenti giornalieri',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ricerca i pagamenti PagoPA ricevuti in una data specifica per riconciliazione',
    },
    {
      id: 'wallet.reportRiconciliazione',
      method: 'GET',
      path: '/api/trpc/wallet.reportRiconciliazione',
      description: 'Report riconciliazione contabile',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Genera report di riconciliazione contabile per periodo',
    },
    {
      id: 'wallet.reportMercato',
      method: 'GET',
      path: '/api/trpc/wallet.reportMercato',
      description: 'Report wallet per mercato',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Genera report aggregato dei wallet per un mercato specifico',
    },

    // ============================================================================
    // IMPRESE & QUALIFICAZIONI - API per gestione imprese e qualificazioni
    // ============================================================================
    {
      id: 'imprese.list',
      method: 'GET',
      path: '/api/imprese',
      description: 'Lista imprese',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco completo delle imprese registrate con filtri opzionali',
    },
    {
      id: 'imprese.getById',
      method: 'GET',
      path: '/api/imprese/:id',
      description: 'Dettaglio impresa',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i dettagli completi di una specifica impresa',
      testParams: { id: 1 },
    },
    {
      id: 'qualificazioni.list',
      method: 'GET',
      path: '/api/qualificazioni',
      description: 'Lista qualificazioni',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco delle qualificazioni disponibili',
    },
    {
      id: 'imprese.qualificazioni',
      method: 'GET',
      path: '/api/imprese/:id/qualificazioni',
      description: 'Qualificazioni impresa',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna le qualificazioni associate a una specifica impresa',
      testParams: { id: 1 },
    },
    {
      id: 'imprese.rating',
      method: 'GET',
      path: '/api/imprese/:id/rating',
      description: 'Semaforo Conformità impresa',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Calcola e ritorna il rating di conformità (semaforo) per una impresa',
      testParams: { id: 1 },
    },
    {
      id: 'imprese.migratePdnd',
      method: 'POST',
      path: '/api/admin/migrate-pdnd',
      description: 'Migrazione PDND',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Avvia la migrazione dei dati imprese verso PDND (Piattaforma Digitale Nazionale Dati)',
    },

    // ============================================================================
    // CONCESSIONI - Gestione concessioni posteggi mercatali
    // ============================================================================
    {
      id: 'concessioni.list',
      method: 'GET',
      path: '/api/concessions',
      description: 'Lista concessioni',
      category: 'concessioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna l\'elenco completo delle concessioni attive',
    },
    {
      id: 'concessioni.getById',
      method: 'GET',
      path: '/api/concessions/:id',
      description: 'Dettaglio concessione',
      category: 'concessioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna i dettagli completi di una concessione specifica',
      testParams: { id: 36 },
    },
    {
      id: 'concessioni.create',
      method: 'POST',
      path: '/api/concessions',
      description: 'Crea concessione',
      category: 'concessioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea una nuova concessione (assegnazione posteggio)',
    },
    {
      id: 'concessioni.createFull',
      method: 'POST',
      path: '/api/concessions/full',
      description: 'Crea concessione completa da SCIA',
      category: 'concessioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea concessione con tutti i 60+ campi da SCIA, gestisce subingresso automatico',
    },
    {
      id: 'concessioni.update',
      method: 'PUT',
      path: '/api/concessions/:id',
      description: 'Aggiorna concessione',
      category: 'concessioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna tutti i campi di una concessione esistente',
      testParams: { id: 36 },
    },
    {
      id: 'concessioni.patch',
      method: 'PATCH',
      path: '/api/concessions/:id',
      description: 'Aggiorna parziale concessione',
      category: 'concessioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna campi specifici: stato, scia_id, comune_rilascio, durata_anni',
      testParams: { id: 36 },
    },
    {
      id: 'concessioni.delete',
      method: 'DELETE',
      path: '/api/concessions/:id',
      description: 'Elimina concessione',
      category: 'concessioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Elimina una concessione e libera il posteggio',
      testParams: { id: 36 },
    },
    {
      id: 'concessioni.associaPosteggio',
      method: 'POST',
      path: '/api/concessions/:id/associa-posteggio',
      description: 'Associa posteggio a concessione',
      category: 'concessioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Associa un posteggio a una concessione esistente',
      testParams: { id: 36 },
    },

    // ============================================================================
    // SUAP - Pratiche SCIA e workflow
    // ============================================================================
    {
      id: 'suap.stats',
      method: 'GET',
      path: '/api/suap/stats',
      description: 'Statistiche SUAP',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna statistiche aggregate delle pratiche SUAP',
    },
    {
      id: 'suap.pratiche.list',
      method: 'GET',
      path: '/api/suap/pratiche',
      description: 'Lista pratiche SCIA',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna tutte le pratiche SCIA con filtri opzionali',
    },
    {
      id: 'suap.pratiche.get',
      method: 'GET',
      path: '/api/suap/pratiche/:id',
      description: 'Dettaglio pratica SCIA',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna dettagli completi di una pratica SCIA con checks, eventi, documenti',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.pratiche.create',
      method: 'POST',
      path: '/api/suap/pratiche',
      description: 'Crea pratica SCIA',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea una nuova pratica SCIA nel sistema',
    },
    {
      id: 'suap.pratiche.patch',
      method: 'PATCH',
      path: '/api/suap/pratiche/:id',
      description: 'Aggiorna pratica SCIA',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna campi pratica: concessione_id, stato, note, esito',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.pratiche.valuta',
      method: 'POST',
      path: '/api/suap/pratiche/:id/valuta',
      description: 'Valuta pratica SCIA',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Esegue valutazione automatica della pratica SCIA',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.pratiche.stato',
      method: 'POST',
      path: '/api/suap/pratiche/:id/stato',
      description: 'Cambia stato pratica',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Cambio stato manuale della pratica con motivazione',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.pratiche.refresh',
      method: 'POST',
      path: '/api/suap/pratiche/:id/refresh',
      description: 'Refresh dati pratica',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna dati pratica con enrichment esterno',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.pratiche.checks',
      method: 'GET',
      path: '/api/suap/pratiche/:id/checks',
      description: 'Lista verifiche pratica',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna tutte le verifiche eseguite sulla pratica',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.pratiche.checks.create',
      method: 'POST',
      path: '/api/suap/pratiche/:id/checks',
      description: 'Registra verifica manuale',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Registra esito di una verifica manuale',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.pratiche.eventi',
      method: 'GET',
      path: '/api/suap/pratiche/:id/eventi',
      description: 'Storico eventi pratica',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna lo storico di tutti gli eventi della pratica',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.pratiche.documenti',
      method: 'GET',
      path: '/api/suap/pratiche/:id/documenti',
      description: 'Lista documenti pratica',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna tutti i documenti allegati alla pratica',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.pratiche.documenti.upload',
      method: 'POST',
      path: '/api/suap/pratiche/:id/documenti',
      description: 'Upload documento pratica',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Carica un documento allegato alla pratica (multipart/form-data)',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.documenti.download',
      method: 'GET',
      path: '/api/suap/documenti/:docId/download',
      description: 'Download documento',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Scarica un documento allegato tramite URL firmato S3',
    },
    {
      id: 'suap.pratiche.azioni',
      method: 'GET',
      path: '/api/suap/pratiche/:id/azioni',
      description: 'Lista azioni workflow',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna tutte le azioni workflow della pratica',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.pratiche.azioni.create',
      method: 'POST',
      path: '/api/suap/pratiche/:id/azioni',
      description: 'Crea azione workflow',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea una nuova azione nel workflow della pratica',
      testParams: { id: 'a23ea538-f523-46c8-aa64-4729388deda5' },
    },
    {
      id: 'suap.regole',
      method: 'GET',
      path: '/api/suap/regole',
      description: 'Lista regole valutazione',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna tutte le regole di valutazione configurate',
    },
    {
      id: 'suap.regole.update',
      method: 'PUT',
      path: '/api/suap/regole/:checkCode',
      description: 'Aggiorna regola valutazione',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna configurazione di una regola di valutazione',
      testParams: { checkCode: 'CHECK_DURC' },
    },
    {
      id: 'suap.import',
      method: 'POST',
      path: '/api/suap/import',
      description: 'Import pratiche SCIA',
      category: 'suap',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Importa pratiche SCIA da file o sistema esterno',
    },

    // ============================================================================
    // WALLETS - Borsellino elettronico PagoPA
    // ============================================================================
    {
      id: 'wallets.list',
      method: 'GET',
      path: '/api/wallets',
      description: 'Lista wallets',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna tutti i wallet attivi nel sistema',
    },
    {
      id: 'wallets.byCompany',
      method: 'GET',
      path: '/api/wallets/company/:companyId',
      description: 'Wallets per impresa',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna tutti i wallet di una specifica impresa',
      testParams: { companyId: 2 },
    },
    {
      id: 'wallets.transactions',
      method: 'GET',
      path: '/api/wallets/:id/transactions',
      description: 'Transazioni wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna lo storico transazioni di un wallet',
      testParams: { id: 1 },
    },
    {
      id: 'wallets.create',
      method: 'POST',
      path: '/api/wallets',
      description: 'Crea wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea un nuovo wallet per una concessione',
    },
    {
      id: 'wallets.init',
      method: 'POST',
      path: '/api/wallets/init',
      description: 'Inizializza schema wallets',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea le tabelle wallets e wallet_transactions se non esistono',
    },
    {
      id: 'wallets.deposit',
      method: 'POST',
      path: '/api/wallets/deposit',
      description: 'Deposito wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Effettua un deposito/ricarica su un wallet',
    },
    {
      id: 'wallets.withdraw',
      method: 'POST',
      path: '/api/wallets/withdraw',
      description: 'Prelievo wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Effettua un prelievo/addebito da un wallet',
    },
    {
      id: 'wallets.calculateFee',
      method: 'POST',
      path: '/api/wallets/calculate-annual-fee',
      description: 'Calcola canone annuale',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Calcola il canone annuale basato su tariffa mercato e mq posteggio',
    },
    {
      id: 'wallets.delete',
      method: 'DELETE',
      path: '/api/wallets/:id',
      description: 'Elimina wallet',
      category: 'wallet',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Elimina un wallet e tutte le sue transazioni',
      testParams: { id: 1 },
    },

    // ============================================================================
    // TARIFFE - Gestione tariffe mercato
    // ============================================================================
    {
      id: 'tariffe.byMarket',
      method: 'GET',
      path: '/api/tariffs/:marketId',
      description: 'Tariffe mercato',
      category: 'tariffe',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna le tariffe configurate per un mercato',
      testParams: { marketId: 1 },
    },
    {
      id: 'tariffe.create',
      method: 'POST',
      path: '/api/tariffs',
      description: 'Crea tariffa',
      category: 'tariffe',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Crea una nuova tariffa per un mercato',
    },

    // ============================================================================
    // QUALIFICAZIONI - Endpoint dedicati
    // ============================================================================
    {
      id: 'qualificazioni.byImpresa',
      method: 'GET',
      path: '/api/qualificazioni/impresa/:impresa_id',
      description: 'Qualificazioni per impresa',
      category: 'qualificazioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna qualificazioni filtrate per impresa',
      testParams: { impresa_id: 2 },
    },
    {
      id: 'qualificazioni.durc',
      method: 'GET',
      path: '/api/qualificazioni/durc/:impresa_id',
      description: 'DURC impresa',
      category: 'qualificazioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna stato DURC di una impresa',
      testParams: { impresa_id: 2 },
    },
    {
      id: 'qualificazioni.durc.create',
      method: 'POST',
      path: '/api/qualificazioni/durc',
      description: 'Crea DURC',
      category: 'qualificazioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Registra un nuovo DURC per una impresa',
    },
    {
      id: 'qualificazioni.suap',
      method: 'GET',
      path: '/api/qualificazioni/suap/:impresa_id',
      description: 'Qualificazioni SUAP impresa',
      category: 'qualificazioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Ritorna qualificazioni SUAP di una impresa',
      testParams: { impresa_id: 2 },
    },
    {
      id: 'qualificazioni.suap.create',
      method: 'POST',
      path: '/api/qualificazioni/suap',
      description: 'Crea qualificazione SUAP',
      category: 'qualificazioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Registra una nuova qualificazione SUAP',
    },
    {
      id: 'qualificazioni.suap.update',
      method: 'PUT',
      path: '/api/qualificazioni/suap/:id',
      description: 'Aggiorna qualificazione SUAP',
      category: 'qualificazioni',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna una qualificazione SUAP esistente',
      testParams: { id: 1 },
    },

    // ============================================================================
    // IMPRESE - Endpoint aggiuntivi
    // ============================================================================
    {
      id: 'imprese.create',
      method: 'POST',
      path: '/api/imprese',
      description: 'Crea impresa',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Registra una nuova impresa nel sistema',
    },
    {
      id: 'imprese.update',
      method: 'PUT',
      path: '/api/imprese/:id',
      description: 'Aggiorna impresa',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna i dati di una impresa esistente',
      testParams: { id: 2 },
    },
    {
      id: 'imprese.qualificazioni.create',
      method: 'POST',
      path: '/api/imprese/:id/qualificazioni',
      description: 'Crea qualificazione impresa',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiunge una nuova qualificazione a una impresa',
      testParams: { id: 2 },
    },
    {
      id: 'imprese.qualificazioni.update',
      method: 'PUT',
      path: '/api/imprese/:id/qualificazioni/:qualId',
      description: 'Aggiorna qualificazione impresa',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna una qualificazione esistente',
      testParams: { id: 2, qualId: 1 },
    },
    {
      id: 'imprese.qualificazioni.delete',
      method: 'DELETE',
      path: '/api/imprese/:id/qualificazioni/:qualId',
      description: 'Elimina qualificazione impresa',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Elimina una qualificazione da una impresa',
      testParams: { id: 2, qualId: 1 },
    },
    {
      id: 'imprese.vetrina',
      method: 'PUT',
      path: '/api/imprese/:id/vetrina',
      description: 'Aggiorna vetrina impresa',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Aggiorna i dati della vetrina pubblica impresa',
      testParams: { id: 2 },
    },
    {
      id: 'imprese.vetrina.upload',
      method: 'POST',
      path: '/api/imprese/:id/vetrina/upload',
      description: 'Upload immagine vetrina',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Carica immagine per la vetrina impresa',
      testParams: { id: 2 },
    },
    {
      id: 'imprese.vetrina.deleteImage',
      method: 'DELETE',
      path: '/api/imprese/:id/vetrina/gallery/:index',
      description: 'Elimina immagine vetrina',
      category: 'imprese',
      status: 'active',
      version: '1.0',
      requiresAuth: true,
      documentation: 'Elimina una immagine dalla galleria vetrina',
      testParams: { id: 2, index: 0 },
    },
    // ============================================================================
    // TCC v2 - WALLET IMPRESA (v5.7.0)
    // Gestione wallet TCC collegati alle imprese con controllo qualifiche
    // ============================================================================
    {
      id: 'tcc.v2.impresa.wallet.get',
      method: 'GET',
      path: '/api/tcc/v2/impresa/:impresaId/wallet',
      description: 'Wallet TCC Impresa - Saldo e stato qualifiche',
      category: 'tcc',
      status: 'active',
      version: '5.7.0',
      requiresAuth: true,
      documentation: 'Recupera il wallet TCC associato all\'impresa con stato qualifiche per semaforo (verde=attivo, rosso=sospeso, grigio=nessuna qualifica)',
      testParams: { impresaId: 38 },
    },
    {
      id: 'tcc.v2.impresa.wallet.create',
      method: 'POST',
      path: '/api/tcc/v2/impresa/:impresaId/wallet/create',
      description: 'Crea Wallet TCC per Impresa',
      category: 'tcc',
      status: 'active',
      version: '5.7.0',
      requiresAuth: true,
      documentation: 'Crea un nuovo wallet TCC per l\'impresa. Lo stato iniziale dipende dalle qualifiche (active se qualificata, suspended altrimenti)',
      testParams: { impresaId: 38 },
    },
    {
      id: 'tcc.v2.impresa.qualification.status',
      method: 'GET',
      path: '/api/tcc/v2/impresa/:impresaId/qualification-status',
      description: 'Stato Qualifiche Impresa per Semaforo',
      category: 'tcc',
      status: 'active',
      version: '5.7.0',
      requiresAuth: true,
      documentation: 'Verifica lo stato delle qualifiche dell\'impresa (DURC, HACCP, etc.) per determinare il colore del semaforo wallet',
      testParams: { impresaId: 38 },
    },
    {
      id: 'tcc.v2.impresa.wallet.status.update',
      method: 'PUT',
      path: '/api/tcc/v2/impresa/:impresaId/wallet/status',
      description: 'Aggiorna Stato Wallet Impresa',
      category: 'tcc',
      status: 'active',
      version: '5.7.0',
      requiresAuth: true,
      documentation: 'Aggiorna manualmente lo stato del wallet impresa (active/suspended). Usato quando cambiano le qualifiche',
      testParams: { impresaId: 38 },
    },
    {
      id: 'tcc.v2.impresa.wallet.transactions',
      method: 'GET',
      path: '/api/tcc/v2/impresa/:impresaId/wallet/transactions',
      description: 'Storico Transazioni Wallet Impresa',
      category: 'tcc',
      status: 'active',
      version: '5.7.0',
      requiresAuth: true,
      documentation: 'Recupera lo storico delle transazioni TCC del wallet impresa (assegnazioni, riscatti, settlement)',
      testParams: { impresaId: 38 },
    },
    {
      id: 'tcc.v2.impresa.wallet.sync',
      method: 'POST',
      path: '/api/tcc/v2/impresa/:impresaId/wallet/sync-qualification',
      description: 'Sincronizza Wallet con Qualifiche',
      category: 'tcc',
      status: 'active',
      version: '5.7.0',
      requiresAuth: true,
      documentation: 'Sincronizza lo stato del wallet con le qualifiche correnti dell\'impresa. Aggiorna wallet_status in base a DURC, HACCP, etc.',
      testParams: { impresaId: 38 },
    },
    {
      id: 'tcc.v2.wallets.all',
      method: 'GET',
      path: '/api/tcc/v2/wallets/all',
      description: 'Lista Tutti i Wallet TCC Imprese',
      category: 'tcc',
      status: 'active',
      version: '5.7.0',
      requiresAuth: true,
      documentation: 'Lista tutti i wallet TCC con stato impresa e qualifiche. Supporta filtro per status e hubId',
    },

    // ============================================================================
    // CANONE UNICO - Sistema Canone Unico Mercatale (v3.55.0+)
    // ============================================================================
    {
      id: 'canone.riepilogo',
      method: 'GET',
      path: '/api/canone-unico/riepilogo',
      description: 'Riepilogo scadenze canone',
      category: 'wallet',
      status: 'active',
      version: '3.55.0',
      requiresAuth: true,
      documentation: 'Ritorna il riepilogo delle scadenze canone con filtri per anno, mercato, tipo operatore (CONCESSION/SPUNTA/STRAORDINARIO)',
      testParams: { anno: 2026, tipo_operatore: 'all' },
    },
    {
      id: 'canone.generaAnnuo',
      method: 'POST',
      path: '/api/canone-unico/genera-canone-annuo',
      description: 'Genera canone annuo',
      category: 'wallet',
      status: 'active',
      version: '3.55.0',
      requiresAuth: true,
      documentation: 'Genera le 4 rate trimestrali del canone annuo per una concessione',
      testParams: { wallet_id: 1, anno: 2026, importo_annuo: 1000 },
    },
    {
      id: 'canone.pagaStraordinario',
      method: 'POST',
      path: '/api/canone-unico/paga-straordinario',
      description: 'Pagamento straordinario',
      category: 'wallet',
      status: 'active',
      version: '3.55.0',
      requiresAuth: true,
      documentation: 'Registra un pagamento straordinario per una singola rata specifica',
    },
    {
      id: 'canone.ricaricheSpunta',
      method: 'GET',
      path: '/api/canone-unico/ricariche-spunta',
      description: 'Ricariche wallet Spunta',
      category: 'wallet',
      status: 'active',
      version: '3.55.0',
      requiresAuth: true,
      documentation: 'Ritorna le ricariche effettuate sui wallet Spunta con filtro per mercato',
      testParams: { mercato_id: 1 },
    },
    {
      id: 'canone.impreseConcessioni',
      method: 'GET',
      path: '/api/canone-unico/imprese-concessioni',
      description: 'Lista imprese per mercato',
      category: 'wallet',
      status: 'active',
      version: '3.58.0',
      requiresAuth: true,
      documentation: 'Ritorna le imprese con concessioni e/o wallet Spunta per un mercato. Supporta filtro tipo_operatore (CONCESSION/SPUNTA/all)',
      testParams: { market_id: 1, tipo_operatore: 'all' },
    },
    {
      id: 'canone.moraSettings',
      method: 'GET',
      path: '/api/canone-unico/mora-settings',
      description: 'Impostazioni mora PA',
      category: 'wallet',
      status: 'active',
      version: '3.46.0',
      requiresAuth: true,
      documentation: 'Ritorna le impostazioni mora (percentuale, giorni grazia) per la PA',
    },
    {
      id: 'canone.updateMoraSettings',
      method: 'PUT',
      path: '/api/canone-unico/mora-settings',
      description: 'Aggiorna impostazioni mora',
      category: 'wallet',
      status: 'active',
      version: '3.46.0',
      requiresAuth: true,
      documentation: 'Aggiorna le impostazioni mora per la PA',
      testParams: { percentuale_mora: 5, giorni_grazia: 15 },
    },

    // ============================================================================
    // PRESENZE E GRADUATORIA (v3.59.0)
    // ============================================================================
    {
      id: 'presenze.getByMercato',
      method: 'GET',
      path: '/api/presenze/mercato/:id',
      description: 'Lista presenze per mercato',
      category: 'wallet',
      status: 'active',
      version: '3.59.0',
      requiresAuth: true,
      documentation: 'Ritorna le presenze registrate per un mercato con filtro tipo (CONCESSION/SPUNTA/STRAORDINARIO)',
      testParams: { tipo: 'all', data: '2026-01-16' },
    },
    {
      id: 'presenze.registra',
      method: 'POST',
      path: '/api/presenze/registra',
      description: 'Registra presenza con calcolo importo e addebito wallet',
      category: 'wallet',
      status: 'active',
      version: '3.59.0',
      requiresAuth: true,
      documentation: 'Registra presenza, calcola importo (Mq x €/mq/giorno), addebita wallet, aggiorna graduatoria',
      testParams: { market_id: 1, stall_id: 1, impresa_id: 1, wallet_id: 1, tipo_presenza: 'SPUNTA' },
    },
    {
      id: 'presenze.checkout',
      method: 'POST',
      path: '/api/presenze/checkout',
      description: 'Registra orario uscita presenza',
      category: 'wallet',
      status: 'active',
      version: '3.59.0',
      requiresAuth: true,
      documentation: 'Registra checkout e orario deposito rifiuti per una presenza',
      testParams: { presenza_id: 1, orario_deposito_rifiuti: '12:00' },
    },
    {
      id: 'graduatoria.getByMercato',
      method: 'GET',
      path: '/api/graduatoria/mercato/:id',
      description: 'Graduatoria presenze per mercato',
      category: 'wallet',
      status: 'active',
      version: '3.59.0',
      requiresAuth: true,
      documentation: 'Ritorna la graduatoria con punteggi, presenze, assenze per tipo operatore',
      testParams: { tipo: 'SPUNTA', anno: 2026 },
    },
    {
      id: 'graduatoria.aggiorna',
      method: 'PUT',
      path: '/api/graduatoria/aggiorna',
      description: 'Aggiorna dati graduatoria (presenze storiche, punteggio)',
      category: 'wallet',
      status: 'active',
      version: '3.59.0',
      requiresAuth: true,
      documentation: 'Permette di modificare presenze totali, punteggio, data prima presenza per caricare storico',
      testParams: { id: 1, presenze_totali: 100, punteggio: 100, data_prima_presenza: '2020-01-01' },
    },
    {
      id: 'graduatoria.assenze',
      method: 'PUT',
      path: '/api/graduatoria/assenze',
      description: 'Aggiorna assenze non giustificate (solo concessionari)',
      category: 'wallet',
      status: 'active',
      version: '3.59.0',
      requiresAuth: true,
      documentation: 'Aggiorna contatore assenze e verifica soglia revoca (1/3 giorni anno)',
      testParams: { id: 1, assenze_non_giustificate: 5 },
    },
    {
      id: 'graduatoria.ricalcolaPosizioni',
      method: 'POST',
      path: '/api/graduatoria/ricalcola-posizioni',
      description: 'Ricalcola posizioni graduatoria',
      category: 'wallet',
      status: 'active',
      version: '3.59.0',
      requiresAuth: true,
      documentation: 'Ricalcola le posizioni in graduatoria per mercato e tipo in base al punteggio',
      testParams: { market_id: 1, tipo: 'SPUNTA' },
    },
    {
      id: 'graduatoria.crea',
      method: 'POST',
      path: '/api/graduatoria/crea',
      description: 'Crea nuovo record graduatoria',
      category: 'wallet',
      status: 'active',
      version: '3.59.0',
      requiresAuth: true,
      documentation: 'Crea un nuovo record in graduatoria per impresa/mercato/tipo',
      testParams: { market_id: 1, impresa_id: 1, wallet_id: 1, tipo: 'SPUNTA' },
    },

    // ============================================================================
    // SUAP NOTIFICHE PM + TEST MERCATO RIFIUTI (v4.6.1)
    // ============================================================================
    {
      id: 'suap.notifichePM',
      method: 'GET',
      path: '/api/suap/notifiche-pm',
      description: 'Notifiche SUAP per Polizia Municipale',
      category: 'suap',
      status: 'active',
      version: '4.6.1',
      requiresAuth: false,
      documentation: 'Raccoglie notifiche da domande_spunta e concessions filtrate per comune_id. Restituisce tipo_pratica, stato, impresa, comune.',
      testParams: { comune_id: 14, limit: 10 },
    },
    {
      id: 'testMercato.registraRifiuti',
      method: 'POST',
      path: '/api/test-mercato/registra-rifiuti',
      description: 'Registra orario deposito rifiuti per tutte le presenze attive',
      category: 'wallet',
      status: 'active',
      version: '4.6.1',
      requiresAuth: false,
      documentation: 'Registra l\'orario di deposito rifiuti per tutte le presenze attive del mercato nella data odierna. Simile al meccanismo chiudi-mercato.',
      testParams: { market_id: 1 },
    },
    {
      id: 'presenze.sessioni',
      method: 'GET',
      path: '/api/presenze/sessioni',
      description: 'Storico sessioni mercato con dettagli',
      category: 'wallet',
      status: 'active',
      version: '4.6.1',
      requiresAuth: false,
      documentation: 'Ritorna lo storico delle sessioni di mercato con filtro per comune_id. Limite default 1000 (rimosso limite 100 precedente).',
      testParams: { comune_id: 14, limit: 50 },
    },

    // ============================================================================
    // VERBALI - Sistema Verbali Professionali PM (L. 689/81)
    // ============================================================================
    {
      id: 'verbali.config',
      method: 'GET',
      path: '/api/verbali/config',
      description: 'Configurazione Comune e Corpo PM per verbali',
      category: 'inspections',
      status: 'active',
      version: '3.80.0',
      requiresAuth: false,
      documentation: 'Ritorna i dati del Comune (nome, provincia, indirizzo, PEC) e del Corpo di Polizia Municipale (comando, telefono, email) per la compilazione automatica dei verbali',
    },
    {
      id: 'verbali.infrazioni',
      method: 'GET',
      path: '/api/verbali/infrazioni',
      description: 'Catalogo infrazioni con testo di legge',
      category: 'inspections',
      status: 'active',
      version: '3.80.0',
      requiresAuth: false,
      documentation: 'Ritorna il catalogo completo delle infrazioni con codice, descrizione, importo minimo/massimo, testo di legge (D.Lgs. 114/98, L. 287/91, ecc.)',
    },
    {
      id: 'verbali.create',
      method: 'POST',
      path: '/api/verbali',
      description: 'Emetti nuovo verbale di contestazione',
      category: 'inspections',
      status: 'active',
      version: '3.80.0',
      requiresAuth: true,
      documentation: 'Crea un nuovo verbale di contestazione conforme alla L. 689/81 con tutti i dati richiesti (agente, trasgressore, infrazione, importo, modalità pagamento)',
      testParams: {
        sanction_id: 1,
        agent_name: 'Mario Rossi',
        agent_badge: 'PM-1234',
        agent_qualifica: 'Agente di Polizia Municipale',
        violation_location: 'Piazza del Popolo',
        violation_date: '2026-01-26',
        violation_time: '10:30',
        transgressor_name: 'Giuseppe Verdi',
        transgressor_cf: 'VRDGPP80A01H501Z',
        amount: 500,
        contestazione_immediata: true
      },
    },
    {
      id: 'verbali.getById',
      method: 'GET',
      path: '/api/verbali/:id',
      description: 'Dettaglio verbale emesso',
      category: 'inspections',
      status: 'active',
      version: '3.80.0',
      requiresAuth: true,
      documentation: 'Ritorna i dettagli completi di un verbale emesso, inclusi dati agente, trasgressore, infrazione, importi e scadenze',
    },
    {
      id: 'verbali.pdf',
      method: 'GET',
      path: '/api/verbali/:id/pdf',
      description: 'Genera PDF verbale conforme',
      category: 'inspections',
      status: 'active',
      version: '3.80.0',
      requiresAuth: true,
      documentation: 'Genera il PDF del verbale in formato conforme alla L. 689/81, pronto per la stampa e notifica',
    },
    {
      id: 'verbali.invia',
      method: 'POST',
      path: '/api/verbali/:id/invia',
      description: 'Invia notifica verbale all\'impresa',
      category: 'inspections',
      status: 'active',
      version: '3.80.0',
      requiresAuth: true,
      documentation: 'Invia la notifica del verbale all\'impresa trasgressore via email/PEC con allegato PDF',
    },

    // ============================================================================
    // MARKET SETTINGS - Impostazioni Orari Mercato e Trasgressioni Automatiche
    // ============================================================================
    {
      id: 'marketSettings.get',
      method: 'GET',
      path: '/api/market-settings/:marketId',
      description: 'Ottieni impostazioni orari mercato',
      category: 'inspections',
      status: 'active',
      version: '3.81.0',
      requiresAuth: true,
      documentation: 'Ritorna le impostazioni degli orari (presenza, spazzatura, uscita) e le regole per verbali automatici di un mercato',
      testParams: { marketId: '1' },
    },
    {
      id: 'marketSettings.save',
      method: 'POST',
      path: '/api/market-settings/:marketId',
      description: 'Salva impostazioni orari mercato',
      category: 'inspections',
      status: 'active',
      version: '3.81.0',
      requiresAuth: true,
      documentation: 'Crea o aggiorna le impostazioni degli orari e le regole per verbali automatici di un mercato',
    },
    {
      id: 'marketTransgressions.list',
      method: 'GET',
      path: '/api/market-settings/transgressions/list',
      description: 'Lista trasgressioni mercato',
      category: 'inspections',
      status: 'active',
      version: '3.81.0',
      requiresAuth: true,
      documentation: 'Ritorna la lista delle trasgressioni rilevate automaticamente con filtri per mercato, stato, tipo e data',
      testParams: { status: 'PENDING', limit: '20' },
    },
    {
      id: 'marketTransgressions.pendingJustifications',
      method: 'GET',
      path: '/api/market-settings/transgressions/pending-justifications',
      description: 'Giustifiche in attesa',
      category: 'inspections',
      status: 'active',
      version: '3.81.0',
      requiresAuth: true,
      documentation: 'Ritorna le trasgressioni in attesa di giustifica o con certificato da valutare',
    },
    {
      id: 'marketTransgressions.justify',
      method: 'POST',
      path: '/api/market-settings/transgressions/:id/justify',
      description: 'Invia giustifica trasgressione',
      category: 'inspections',
      status: 'active',
      version: '3.81.0',
      requiresAuth: true,
      documentation: 'Permette all\'impresa di inviare un certificato di giustifica per una trasgressione',
    },
    {
      id: 'marketTransgressions.review',
      method: 'PUT',
      path: '/api/market-settings/transgressions/:id/review',
      description: 'Approva/Rifiuta giustifica',
      category: 'inspections',
      status: 'active',
      version: '3.81.0',
      requiresAuth: true,
      documentation: 'Permette alla PM di approvare o rifiutare una giustifica inviata dall\'impresa',
    },
    {
      id: 'marketTransgressions.sanction',
      method: 'POST',
      path: '/api/market-settings/transgressions/:id/sanction',
      description: 'Collega verbale a trasgressione',
      category: 'inspections',
      status: 'active',
      version: '3.81.0',
      requiresAuth: true,
      documentation: 'Collega un verbale emesso a una trasgressione rilevata automaticamente',
    },
    {
      id: 'marketTransgressions.stats',
      method: 'GET',
      path: '/api/market-settings/transgressions/stats',
      description: 'Statistiche trasgressioni',
      category: 'inspections',
      status: 'active',
      version: '3.81.0',
      requiresAuth: true,
      documentation: 'Ritorna statistiche aggregate sulle trasgressioni per dashboard',
      testParams: { period: '30d' },
    },
    {
      id: 'marketTransgressions.cronRun',
      method: 'POST',
      path: '/api/market-settings/cron/run',
      description: 'Esegui CRON rilevamento trasgressioni',
      category: 'inspections',
      status: 'active',
      version: '3.81.0',
      requiresAuth: true,
      documentation: 'Esegue manualmente il CRON job per rilevamento trasgressioni e verifica scadenze giustifiche',
    },

    // ============================================================================
    // GAMING & REWARDS - Sistema di Gamification
    // ============================================================================
    {
      id: 'gamingRewards.getConfig',
      method: 'GET',
      path: '/api/trpc/dmsHub.gamingRewards.getConfig',
      description: 'Ottieni configurazione Gaming & Rewards per comune',
      category: 'gaming',
      status: 'active',
      version: '4.0.0',
      requiresAuth: false,
      documentation: 'Ritorna la configurazione completa del sistema Gaming & Rewards per un comune specifico. Include parametri per segnalazioni civiche, mobilità sostenibile, cultura & turismo, acquisti locali e challenge.',
      testParams: { comuneId: 1 },
    },
    {
      id: 'gamingRewards.saveConfig',
      method: 'POST',
      path: '/api/trpc/dmsHub.gamingRewards.saveConfig',
      description: 'Salva configurazione Gaming & Rewards',
      category: 'gaming',
      status: 'active',
      version: '4.0.0',
      requiresAuth: true,
      documentation: 'Salva o aggiorna la configurazione del sistema Gaming & Rewards per un comune. Supporta UPSERT (insert or update).',
    },
    {
      id: 'gamingRewards.getStats',
      method: 'GET',
      path: '/api/trpc/dmsHub.gamingRewards.getStats',
      description: 'Statistiche TCC per comune',
      category: 'gaming',
      status: 'active',
      version: '4.0.0',
      requiresAuth: false,
      documentation: 'Ritorna statistiche aggregate sui TCC per un comune: totale emessi, spesi, transazioni, CO2 risparmiata.',
      testParams: { comuneId: 1 },
    },
    {
      id: 'gamingRewards.getHeatmapPoints',
      method: 'GET',
      path: '/api/trpc/dmsHub.gamingRewards.getHeatmapPoints',
      description: 'Punti heatmap commerciale',
      category: 'gaming',
      status: 'active',
      version: '4.0.0',
      requiresAuth: false,
      documentation: 'Ritorna i punti per la heatmap commerciale: negozi HUB con coordinate e aggregazione TCC (guadagnati/spesi/transazioni).',
      testParams: { comuneId: 1 },
    },

    // ============================================================================
    // GAMING & REWARDS - REST API (Backend Hetzner) - v4.1.0
    // Endpoint per Dashboard PA Gaming & Rewards
    // ============================================================================
    {
      id: 'gamingRewards.rest.config.get',
      method: 'GET',
      path: '/api/gaming-rewards/config',
      description: 'Ottieni configurazione Gaming per comune (REST)',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: false,
      documentation: 'Ritorna la configurazione Gaming & Rewards per un comune specifico. Parametri: comune_id',
      testParams: { comune_id: 1 },
    },
    {
      id: 'gamingRewards.rest.config.create',
      method: 'POST',
      path: '/api/gaming-rewards/config',
      description: 'Crea configurazione Gaming per comune',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: true,
      documentation: 'Crea una nuova configurazione Gaming & Rewards per un comune',
    },
    {
      id: 'gamingRewards.rest.config.update',
      method: 'PUT',
      path: '/api/gaming-rewards/config',
      description: 'Aggiorna configurazione Gaming per comune',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: true,
      documentation: 'Aggiorna la configurazione Gaming & Rewards esistente per un comune',
    },
    {
      id: 'gamingRewards.rest.stats',
      method: 'GET',
      path: '/api/gaming-rewards/stats',
      description: 'Statistiche TCC aggregate per comune',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: false,
      documentation: 'Ritorna statistiche aggregate: TCC emessi, spesi, utenti attivi, CO2 risparmiata',
      testParams: { comune_id: 1 },
    },
    {
      id: 'gamingRewards.rest.heatmap',
      method: 'GET',
      path: '/api/gaming-rewards/heatmap',
      description: 'Heatmap transazioni TCC',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: false,
      documentation: 'Ritorna punti per heatmap transazioni TCC con coordinate e aggregazioni',
      testParams: { comune_id: 1 },
    },
    {
      id: 'gamingRewards.rest.topShops',
      method: 'GET',
      path: '/api/gaming-rewards/top-shops',
      description: 'Top 5 negozi per TCC guadagnati',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: false,
      documentation: 'Ritorna i top 5 negozi per TCC guadagnati con transazioni',
      testParams: { comune_id: 1 },
    },
    {
      id: 'gamingRewards.rest.trend',
      method: 'GET',
      path: '/api/gaming-rewards/trend',
      description: 'Trend TCC ultimi 7 giorni',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: false,
      documentation: 'Ritorna trend giornaliero TCC guadagnati/spesi e segnalazioni civiche',
      testParams: { comune_id: 1 },
    },

    // ============================================================================
    // MOBILITÀ SOSTENIBILE - REST API (Backend Hetzner) - v4.1.0
    // Endpoint per tracciamento percorsi e fermate trasporto pubblico
    // ============================================================================
    {
      id: 'gamingRewards.mobility.startTracking',
      method: 'POST',
      path: '/api/gaming-rewards/mobility/start-tracking',
      description: 'Avvia tracciamento percorso mobilità',
      category: 'mobility',
      status: 'active',
      version: '4.1.0',
      requiresAuth: true,
      documentation: 'Avvia il tracciamento di un percorso (bus, bici, piedi). Registra punto di partenza e tipo trasporto',
    },
    {
      id: 'gamingRewards.mobility.complete',
      method: 'POST',
      path: '/api/gaming-rewards/mobility/complete',
      description: 'Completa percorso e assegna TCC',
      category: 'mobility',
      status: 'active',
      version: '4.1.0',
      requiresAuth: true,
      documentation: 'Completa un percorso tracciato, calcola km e CO2 risparmiata, assegna TCC reward',
    },
    {
      id: 'gamingRewards.mobility.history',
      method: 'GET',
      path: '/api/gaming-rewards/mobility/history',
      description: 'Storico percorsi utente',
      category: 'mobility',
      status: 'active',
      version: '4.1.0',
      requiresAuth: true,
      documentation: 'Ritorna lo storico dei percorsi completati dall\'utente con km, CO2 e TCC',
    },
    {
      id: 'gamingRewards.mobility.stats',
      method: 'GET',
      path: '/api/gaming-rewards/mobility/stats',
      description: 'Statistiche mobilità sostenibile',
      category: 'mobility',
      status: 'active',
      version: '4.1.0',
      requiresAuth: false,
      documentation: 'Ritorna statistiche aggregate: km totali, CO2 risparmiata, percorsi completati',
      testParams: { comune_id: 1 },
    },
    {
      id: 'gamingRewards.mobility.heatmap',
      method: 'GET',
      path: '/api/gaming-rewards/mobility/heatmap',
      description: 'Heatmap fermate trasporto pubblico (GTFS)',
      category: 'mobility',
      status: 'active',
      version: '4.1.0',
      requiresAuth: false,
      documentation: 'Ritorna fermate trasporto pubblico da GTFS con coordinate. Supporta filtro per lat/lng/radius',
      testParams: { lat: 44.49, lng: 11.34, radius: 10 },
    },

    // ============================================================================
    // CULTURA & TURISMO - REST API (Backend Hetzner) - v4.1.0
    // Endpoint per POI culturali da OpenStreetMap
    // ============================================================================
    {
      id: 'gamingRewards.culture.checkin',
      method: 'POST',
      path: '/api/gaming-rewards/culture/checkin',
      description: 'Check-in luogo culturale',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: true,
      documentation: 'Registra un check-in in un luogo culturale (museo, monumento, ecc.) e assegna TCC reward',
    },
    {
      id: 'gamingRewards.culture.history',
      method: 'GET',
      path: '/api/gaming-rewards/culture/history',
      description: 'Storico visite culturali utente',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: true,
      documentation: 'Ritorna lo storico delle visite culturali dell\'utente con TCC guadagnati',
    },
    {
      id: 'gamingRewards.culture.stats',
      method: 'GET',
      path: '/api/gaming-rewards/culture/stats',
      description: 'Statistiche cultura e turismo',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: false,
      documentation: 'Ritorna statistiche aggregate: visite totali, POI più visitati, TCC assegnati',
      testParams: { comune_id: 1 },
    },
    {
      id: 'gamingRewards.culture.heatmap',
      method: 'GET',
      path: '/api/gaming-rewards/culture/heatmap',
      description: 'Heatmap POI culturali (OpenStreetMap)',
      category: 'gaming',
      status: 'active',
      version: '4.1.0',
      requiresAuth: false,
      documentation: 'Ritorna POI culturali da OpenStreetMap: musei, castelli, monumenti, teatri, siti archeologici. Supporta filtro per lat/lng/radius/type/region',
      testParams: { lat: 44.49, lng: 11.34, radius: 15 },
    },

    // ============================================================================
    // PDND - Piattaforma Digitale Nazionale Dati + ANPR
    // ============================================================================
    {
      id: 'pdnd.getStatus',
      method: 'GET',
      path: '/api/trpc/pdnd.getStatus',
      description: 'Stato connessione PDND',
      category: 'pdnd',
      status: 'beta',
      version: '1.0.0',
      requiresAuth: true,
      documentation: 'Verifica stato della connessione PDND (mock o live), configurazione chiavi RSA e purpose ID',
    },
    {
      id: 'pdnd.listEServices',
      method: 'GET',
      path: '/api/trpc/pdnd.listEServices',
      description: 'Lista e-Service PDND',
      category: 'pdnd',
      status: 'beta',
      version: '1.0.0',
      requiresAuth: true,
      documentation: 'Ritorna i 3 e-Service esposti: dms-mercati, dms-concessioni, dms-operatori con stato di pubblicazione',
    },
    {
      id: 'pdnd.publishEService',
      method: 'POST',
      path: '/api/trpc/pdnd.publishEService',
      description: 'Pubblica e-Service su PDND',
      category: 'pdnd',
      status: 'beta',
      version: '1.0.0',
      requiresAuth: true,
      documentation: 'Pubblica un e-Service su PDND Interop. Input: serviceId (dms-mercati|dms-concessioni|dms-operatori) + metadata',
    },
    {
      id: 'pdnd.testConnection',
      method: 'POST',
      path: '/api/trpc/pdnd.testConnection',
      description: 'Test connettivita\' PDND',
      category: 'pdnd',
      status: 'beta',
      version: '1.0.0',
      requiresAuth: true,
      documentation: 'Testa la connettivita\' verso PDND generando un voucher JWT e verificando la risposta',
    },
    {
      id: 'pdnd.verificaCF',
      method: 'GET',
      path: '/api/trpc/pdnd.verificaCF',
      description: 'Verifica Codice Fiscale (ANPR via PDND)',
      category: 'pdnd',
      status: 'beta',
      version: '1.0.0',
      requiresAuth: true,
      documentation: 'Verifica esistenza di un codice fiscale su ANPR tramite PDND. Ritorna dati anagrafici (nome, cognome, data nascita)',
      testParams: { codiceFiscale: 'RSSMRA85M01H501Z' },
    },
    {
      id: 'pdnd.verificaResidenza',
      method: 'GET',
      path: '/api/trpc/pdnd.verificaResidenza',
      description: 'Verifica Residenza (ANPR via PDND)',
      category: 'pdnd',
      status: 'beta',
      version: '1.0.0',
      requiresAuth: true,
      documentation: 'Lookup residenza da codice fiscale su ANPR via PDND. Ritorna indirizzo, CAP, comune, provincia',
      testParams: { codiceFiscale: 'RSSMRA85M01H501Z' },
    },

    // ============================================================================
    // APP IO - Notifiche cittadini tramite App IO
    // ============================================================================
    {
      id: 'appIo.sendNotification',
      method: 'POST',
      path: '/api/trpc/appIo.sendNotification',
      description: 'Invia notifica App IO',
      category: 'appio',
      status: 'beta',
      version: '1.0.0',
      requiresAuth: true,
      documentation: 'Invia una notifica a un cittadino tramite App IO usando template predefiniti (scadenza_concessione, avviso_pagamento, verbale_emesso, conferma_prenotazione)',
    },
    {
      id: 'appIo.checkProfile',
      method: 'GET',
      path: '/api/trpc/appIo.checkProfile',
      description: 'Verifica profilo App IO',
      category: 'appio',
      status: 'beta',
      version: '1.0.0',
      requiresAuth: true,
      documentation: 'Verifica se un cittadino ha App IO attiva e quali canali di notifica sono abilitati',
      testParams: { fiscalCode: 'RSSMRA85M01H501Z' },
    },
    {
      id: 'appIo.getStatus',
      method: 'GET',
      path: '/api/trpc/appIo.getStatus',
      description: 'Stato connessione App IO',
      category: 'appio',
      status: 'beta',
      version: '1.0.0',
      requiresAuth: true,
      documentation: 'Verifica stato della connessione App IO (mock o live), API key configurata, numero template disponibili',
    },
    {
      id: 'appIo.listTemplates',
      method: 'GET',
      path: '/api/trpc/appIo.listTemplates',
      description: 'Lista template notifiche App IO',
      category: 'appio',
      status: 'beta',
      version: '1.0.0',
      requiresAuth: true,
      documentation: 'Ritorna i 4 template messaggi predefiniti: scadenza_concessione, avviso_pagamento, verbale_emesso, conferma_prenotazione',
    },
  ];
}

/**
 * Filtra gli endpoint per categoria
 */
export function getAPIsByCategory(category: APIEndpoint['category']): APIEndpoint[] {
  return getAPIInventory().filter(api => api.category === category);
}

/**
 * Cerca un endpoint per ID
 */
export function getAPIById(id: string): APIEndpoint | undefined {
  return getAPIInventory().find(api => api.id === id);
}

/**
 * Statistiche sull'inventario API
 * 
 * Il totale viene letto dinamicamente dal backend Hetzner tramite
 * GET /api/dashboard/integrations/endpoint-count
 * 
 * L'inventario documentato contiene solo gli endpoint principali monitorati da Guardian.
 */
export function getAPIStats() {
  const inventory = getAPIInventory();
  const byCategory = inventory.reduce((acc, api) => {
    acc[api.category] = (acc[api.category] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const byStatus = inventory.reduce((acc, api) => {
    acc[api.status] = (acc[api.status] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  return {
    total: inventory.length, // Questo verrà sovrascritto dal valore dinamico del backend
    documented: inventory.length,
    byCategory,
    byStatus,
    requiresAuth: inventory.filter(api => api.requiresAuth).length,
    public: inventory.filter(api => !api.requiresAuth).length,
  };
}

/**
 * Ottiene il conteggio dinamico degli endpoint dal backend Hetzner
 */
export async function getDynamicEndpointCount(): Promise<number> {
  try {
    const response = await fetch('https://api.mio-hub.me/api/dashboard/integrations/endpoint-count');
    if (!response.ok) throw new Error('Failed to fetch endpoint count');
    const data = await response.json();
    return data.total || 0;
  } catch (error) {
    console.error('Error fetching dynamic endpoint count:', error);
    return 0;
  }
}
